use_frameworks!

platform :ios, '9.0'

target 'AudioEqualizer_Example' do
  pod 'AudioEqualizer', :path => '../'

  target 'AudioEqualizer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
