platform :ios, '8.0'
use_frameworks!

target 'NvMimo_Example' do
  
  pod 'NvMimo', :path => '../'
  pod 'Masonry', :git => 'https://gitee.com/mirrors/ios-masonry.git',:tag => 'v1.1.0'
  pod 'SDWebImage',    :git => 'https://gitee.com/mirrors/SDWebImage.git',:tag => '5.9.5'
  pod 'MBProgressHUD', :git => 'https://gitee.com/mirrors/MBProgressHUD.git',:tag => '1.1.0'
  pod 'YYModel',       :git => 'https://gitee.com/mirrors/YYModel.git',:tag => '1.0.4'
  pod 'SSZipArchive',  :git => 'https://gitee.com/chuyang009/ZipArchive.git',:tag => 'v2.2.2'
  pod 'AFNetworking',  :git => 'https://gitee.com/mirrors/AFNetworking.git',:tag => '3.2.1'
  pod 'Reachability',  :git => 'https://gitee.com/mirrors/Reachability.git',:tag => 'v3.2'
    
end
