use_frameworks!

platform :ios, '8.0'

target 'NvSDKCommon_Example' do
  pod 'NvSDKCommon', :path => '../'
  pod 'NvBaseCommon', :path => '../../../SubProject/NvBaseCommon/'

  pod 'Masonry',       :git => 'https://gitee.com/mirrors/ios-masonry.git',:tag => 'v1.1.0'
  pod 'MBProgressHUD', :git => 'https://gitee.com/mirrors/MBProgressHUD.git',:tag => '1.1.0'
  pod 'AFNetworking',  :git => 'https://gitee.com/mirrors/AFNetworking.git',:tag => '3.2.1'
end
